import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

live_config_reload = true

[font]
size = 14.0

[font.normal]
family = "MonaspiceNe Nerd Font Mono"
style = "Light"

[font.bold]
style = "Medium"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u0001\u006e"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001\u0070"
key = "P"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001\u0028"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001\u0029"
key = "K"
mods = "Control|Shift"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 25000
multiplier = 1

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
option_as_alt = "OnlyLeft"
padding = { x = 2 }
