#!/bin/zsh

SUBMODULES="\
vim-minibufexpl git://github.com/fholgado/minibufexpl.vim.git
vim-nerdtree git://github.com/scrooloose/nerdtree.git
vim-fugitive git://github.com/tpope/vim-fugitive.git
vim-surround git://github.com/tpope/vim-surround.git
vim-repeat git://github.com/tpope/vim-repeat.git
vim-command-t git://git.wincent.com/command-t.git
vim-guicolorscheme git://github.com/thinca/vim-guicolorscheme.git
vim-csapprox git://github.com/godlygeek/csapprox.git
vim-nerdcommenter git://github.com/scrooloose/nerdcommenter.git
vim-supertab git://github.com/ervandew/supertab.git
vim-addon-mw-utils git://github.com/MarcWeber/vim-addon-mw-utils.git
vim-snipmate git://github.com/garbas/vim-snipmate.git
vim-snipmate-snippets git://github.com/honza/snipmate-snippets.git
vim-arpeggio git://github.com/kana/vim-arpeggio.git
vim-checksyntax git://github.com/tomtom/checksyntax_vim.git
vim-quickfixsigns git://github.com/tomtom/quickfixsigns_vim.git
vim-tlib git://github.com/tomtom/tlib_vim.git
vim-fuzzyfinder git://github.com/vim-scripts/FuzzyFinder.git
vim-l9 git://github.com/vim-scripts/L9.git
vim-clang-complete git://github.com/Rip-Rip/clang_complete.git \
"

IFS=$' '
echo $SUBMODULES | while read name url;
do
    if [[ -z $2 || $2 = $name ]]; then
        case $1 in
            add)
                echo "add: $name $url";
                git remote add $name $url;
                ;;
            fetch)
                echo "fetch: $name";
                git fetch $name;
                ;;
            rm)
                echo "remove: $name";
                git remote rm $name;
                ;;
            list)
                echo "$name: $url";
                ;;
            update)
                echo "update subtree: $name";
                git subtree merge --squash -P "vim/bundle/$name" "$name/master";
                ;;
        esac
    fi
done

exit 0
