#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Marc Winners"
email = "git@mw.mozmail.com"

[ui]
default-command = "jjui"
diff-editor = "diffview"
diff-formatter = "delta"
merge-editor = "diffview"
show-cryptographic-signatures = true

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]
diff-args = [
  "--diff-so-fancy",
  "--file-decoration-style",
  "omit",
  "--hunk-header-decoration-style",
  "omit",
  "$left",
  "$right",
]

[merge-tools.diffview]
program = "sh"
diff-args = [
  "-c",
  'exec "$HOME/dots/config/jj/diffview" dirs "$1" "$2"',
  "",
  "$left",
  "$right",
]
edit-args = [
  "-c",
  'exec "$HOME/dots/config/jj/diffview" dirs "$1" "$2"',
  "",
  "$left",
  "$right",
]
merge-args = [
  "-c",
  'exec "$HOME/dots/config/jj/diffview" merge "$1" "$2" "$3"',
  "",
  "$output",
  "$left",
  "$right",
]
merge-tool-edits-conflict-markers = true

[aliases]
jjui = ["util", "exec", "--", "jjui"]

# temporary hack until jj adds colocated workspaces
workspace-add = [
  "util",
  "exec",
  "--",
  "sh",
  "-c",
  '''
set -eu
jj workspace add "$1"
cd "$1"
echo "gitdir: $(jj git root)" > .git
''',
  "",
]

[git]
private-commits = '''description('private:*')'''
