#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Marc Winners"
email = "git@mw.mozmail.com"

[ui]
default-command = "jjui"
diff-formatter = "difft"

[aliases]
jjui = ["util", "exec", "--", "jjui"]

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]
