command_timeout = 50
format = """
${directory}\
${custom.jj}\
${custom.git_branch}\
${custom.git_status}\
${cmd_duration}\
${line_break}\
${jobs}\
${time}\
${status}\
${shell}\
${character}"""

[custom.jj]
when = "jj --ignore-working-copy root"
symbol = " "
command = '''
jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template '
  separate(" ",
    change_id.shortest(4),
    bookmarks,
    concat(
      if(conflict, "󰞇 "),
      if(divergent, " "),
      if(hidden, "󰘓 "),
      if(immutable, " "),
      if(empty, "(empty)")
    ),
  )
'
'''

[custom.git_status]
when = "! jj --ignore-working-copy root"
command = "starship module git_status"
style = ""

[custom.git_branch]
when = "! jj --ignore-working-copy root"
command = "starship module git_branch"
style = ""

[git_status]
disabled = true

[git_commit]
disabled = true

[git_metrics]
disabled = true

[git_branch]
disabled = true
